#!/usr/bin/env bash
# _genonce.sh — generated by Torch · torchlab.dev
# Based on HL7 ig-publisher-scripts; enhanced with shared publisher.jar via ~/.torch/
# Note: the publisher automatically shares its terminology cache at ~/fhircache

TORCH_DIR="$HOME/.torch"

export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

echo "Checking internet connection..."
if curl -s --max-time 4 https://tx.fhir.org/r4/metadata -o /dev/null 2>&1; then
  echo "Online"
  TX_OPT=""
else
  echo "Offline — terminology validation disabled"
  TX_OPT="-tx n/a"
fi

# Resolve publisher — shared first, then local, then parent
if   [ -f "$TORCH_DIR/publisher.jar" ]; then JAR="$TORCH_DIR/publisher.jar"
elif [ -f "input-cache/publisher.jar"  ]; then JAR="input-cache/publisher.jar"
elif [ -f "../publisher.jar"            ]; then JAR="../publisher.jar"
else
  echo "publisher.jar not found. Run ./_updatePublisher.sh first."
  exit 1
fi

echo "Publisher : $JAR"

java -jar "$JAR" -ig . $TX_OPT "$@"
