@ECHO OFF
REM _genonce.bat — generated by Torch · torchlab.dev
REM Enhanced with shared publisher.jar via %USERPROFILE%\.torch\
REM Note: the publisher automatically shares its terminology cache at %USERPROFILE%\fhircache

SET TORCH_DIR=%USERPROFILE%\.torch
SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

ECHO Checking internet connection...
powershell -Command "try{$r=[System.Net.WebRequest]::Create('https://tx.fhir.org/r4/metadata');$r.Timeout=4000;$r.GetResponse().Close();exit 0}catch{exit 1}"
IF %ERRORLEVEL% EQU 0 (
  ECHO Online
  SET TX_OPT=
) ELSE (
  ECHO Offline - terminology validation disabled
  SET TX_OPT=-tx n/a
)

IF EXIST "%TORCH_DIR%\publisher.jar" (
  SET JAR=%TORCH_DIR%\publisher.jar
) ELSE IF EXIST "%CD%\input-cache\publisher.jar" (
  SET JAR=%CD%\input-cache\publisher.jar
) ELSE IF EXIST "..\publisher.jar" (
  SET JAR=..\publisher.jar
) ELSE (
  ECHO publisher.jar not found. Run _updatePublisher.bat first.
  PAUSE
  EXIT /B 1
)

ECHO Publisher : %JAR%

JAVA -jar "%JAR%" -ig . %TX_OPT% %*
PAUSE
