#!/usr/bin/env bash
# _updatePublisher.sh — generated by Torch · torchlab.dev
# Downloads publisher.jar to ~/.torch/ (shared across all IGs).
# A copy is placed in ./input-cache/ for compatibility with standard tooling.

TORCH_DIR="$HOME/.torch"
SHARED_JAR="$TORCH_DIR/publisher.jar"
LOCAL_CACHE="input-cache"
LOCAL_JAR="$LOCAL_CACHE/publisher.jar"
DLURL="https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar"

echo "Checking internet connection..."
if ! curl -s --max-time 4 https://tx.fhir.org/r4/metadata -o /dev/null 2>&1; then
  echo "Offline — cannot update publisher."
  exit 1
fi

mkdir -p "$TORCH_DIR" "$LOCAL_CACHE"

echo "Downloading IG Publisher (~100 MB) to shared location..."
if curl -L --progress-bar "$DLURL" -o "$SHARED_JAR"; then
  echo "Saved : $SHARED_JAR"
  # Symlink into input-cache so _genonce fallback and standard tools work
  ln -sf "$SHARED_JAR" "$LOCAL_JAR" 2>/dev/null || cp "$SHARED_JAR" "$LOCAL_JAR"
  echo "Linked: $LOCAL_JAR"
else
  echo "Download failed."
  exit 1
fi
