@ECHO OFF
REM _updatePublisher.bat — generated by Torch · torchlab.dev
REM Downloads publisher.jar to %USERPROFILE%\.torch\ (shared across all IGs).
REM A copy is placed in .\input-cache\ for compatibility with standard tooling.

SET TORCH_DIR=%USERPROFILE%\.torch
SET SHARED_JAR=%TORCH_DIR%\publisher.jar
SET LOCAL_CACHE=%CD%\input-cache
SET LOCAL_JAR=%LOCAL_CACHE%\publisher.jar
SET DLURL=https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar

ECHO Checking internet connection...
powershell -Command "try{$r=[System.Net.WebRequest]::Create('https://tx.fhir.org/r4/metadata');$r.Timeout=4000;$r.GetResponse().Close();exit 0}catch{exit 1}"
IF %ERRORLEVEL% NEQ 0 (
  ECHO Offline - cannot update publisher.
  PAUSE & EXIT /B 1
)

IF NOT EXIST "%TORCH_DIR%"    MKDIR "%TORCH_DIR%"
IF NOT EXIST "%LOCAL_CACHE%"  MKDIR "%LOCAL_CACHE%"

ECHO Downloading IG Publisher to shared location (~100 MB)...
powershell -Command "if('System.Net.WebClient' -as [type]){(new-object System.Net.WebClient).DownloadFile('%DLURL%','%SHARED_JAR%')}else{Invoke-WebRequest -Uri '%DLURL%' -Outfile '%SHARED_JAR%'}"

IF EXIST "%SHARED_JAR%" (
  ECHO Saved : %SHARED_JAR%
  COPY /Y "%SHARED_JAR%" "%LOCAL_JAR%" >NUL
  ECHO Copied: %LOCAL_JAR%
) ELSE (
  ECHO Download failed.
  PAUSE & EXIT /B 1
)
PAUSE
